### PR TITLE
There is bug that it doesn't invoke completion block when it dismiss with gesture 

### PR DESCRIPTION
**Pull request by dKasabwala**

### CODE REVIEW

**Comment by mwfire** [comment]
I cannot reproduce this. All examples in this project behave as expected. By design, completion is called on deinit of the dialog, so is it possible you are dealing with a retain cycle with a custom view controller?

**Comment by dKasabwala** [comment]
@mwfire yea It could be , let me just make sure of it

**Comment by dKasabwala** [comment]
Ok there was a memory leak ,actually i called popup dismiss inside cancel button block

**Comment by mwfire** [comment]
@Dipak99041012, ah, ok! So if there are any questions, just file an issue. I will close this for now. Thanks for contributing!

**Pull request closed without merging**
