### PR TITLE
Swift 5 update

### PR DESCRIPTION
**Pull request by Maryom**
Thanks for this awesome repo. 👌🏼

### CODE REVIEW

**Comment by mwfire** [comment]
Hey there! Thanks a lot for your contribution. Please make sure to work on the Swift 5 branch, please: https://github.com/Orderella/PopupDialog/tree/Swift5

Otherwise we will duplicate our efforts ;)

Thanks a lot!

**Comment by Maryom** [comment]
OMG! I didn't notice that there is a Swift 5 branch 🤦‍♀️

Thank you.

**Comment by mwfire** [comment]
No problem, thank you! I am basically currently struggling with getting Travis CI to run. It does not recognize the device identifier, so prewarming the simulator fails. The real tests, however, pass. I am thinking of removing the failing command for testing purposes :) It's kinda trial and error ;)

**Comment by Maryom** [comment]
@Mazyod has an awesome experience in this 👍🏼

**Comment by mwfire** [comment]
Ok, just commented out the prewarming. One thing I noticed is that apparently, simulators now seem to have different names with iOS 12.2. Like ` iPhone Xʀ` vs. ` iPhone XR`.

> @Mazyod has an awesome experience in this 👍🏼

If Travis builds keep failing, I might indeed need some advice :)

**Comment by Maryom** [comment]
@mwfire I can't install it I got:

```
[!] CocoaPods could not find compatible versions for pod "PopupDialog":
  In Podfile:
    PopupDialog (~> 1.1)
```

**Comment by mwfire** [comment]
Nope, it's not yet published, as of the failing CI builds. I will merge as soon as I have fixed it (today). Until then you will have to specify the branch in your pod file. :(

**Comment by Maryom** [comment]
Ok thanks.

**Comment by mwfire** [comment]
@Maryom Ok, 1.1.0 is available now!

**Comment by Maryom** [comment]
Great :) thank you.

**Pull request closed without merging**
