### PR TITLE
Animate to another view support

### PR DESCRIPTION
**Pull request by ergunkocak**

### CODE REVIEW

**Comment by ergunkocak** [comment]
Hi,

I am very eager to have this merged :) Is there any problem preventing it to be merged? If there is, please tell me so i can fix it.

Best

**Comment by ergunkocak** [comment]
All checks passed and no merge conflicts 🎉

**Comment by ergunkocak** [comment]
Hi,

Is there anything i can do to have this merged?

Best

**Comment by mwfire** [comment]
Hey there. Thanks for your PR. We are considering this to be merged. However, new features are more easily discussed in the issue tracker. This way we can evaluate how many users want this feature and how generic it should be. We are trying to keep this library as slick as we can, so I will come back to you as soon as we have a final decision. Apologies that it took a while...

Cheers
Martin

**Comment by ergunkocak** [comment]
Hi,

If it will take time to consider. Would you at least provide a way so i can use this by extending the library. Some stuff is private so i can not extend the library if i use it like a cocoapod. 
Currently i have to include the library and add the extension in core files.

Best

**Comment by JohnKuan** [comment]
Hi, 

I am looking for a solution similar to what @ergunkocak has proposed in this PR. If this PR can be merged, I will have a use for it. Otherwise, as what he has requested, could you expose the necessary `popupContainerView` so that it can be extended.

Thank you.

**Comment by shmakovigor** [comment]
Hello! That would be great to have this feature in the library!

**Pull request closed without merging**
