### PR TITLE
Dependencies to Swift 5.0

### PR DESCRIPTION
**Pull request by maxxfrazer**
- Bumped DynamicBlurView version using swift 5.0
- Similar changes with bumping the versions in Example project

Of course let me know if there's a preferred branch for this PR such as development

### CODE REVIEW

**Comment by maxxfrazer** [comment]
@mwfire Just checking if you've seen this PR?
The only real change was:
https://github.com/Orderella/PopupDialog/pull/320/files#diff-18f26ca2a38973307ca1bdffc7845839L15
The rest is a result of updating pods which are included in this repo

**Comment by abbood** [comment]
i tried running based on your code.. but it's not compiling:
image

did you test it?

**Comment by maxxfrazer** [comment]
> i tried running based on your code.. but it's not compiling:
> image
> 
> did you test it?

Yes, I did test, and Travis CI compiles the updates with no issues. It's likely an error on your end

Looks like it can't find this function which is defined here:
https://github.com/KyoheiG3/DynamicBlurView/blob/579c6a26e72cd6535da44c1b7a0afd587e5b02b4/DynamicBlurView/UIImage%2BBlur.swift

**Comment by soucolline** [comment]
Just checked @maxxfrazer branch and everything is working fine for me 👍
Any updates on this PR ? would be great to remove those nasty warnings 🙏

**Comment by maxxfrazer** [comment]
@mwfire any chance this PR could be looked at? should be ready to go

**Comment by maxxfrazer** [comment]
@mwfire keen to get this PR merged

**Comment by maxxfrazer** [comment]
@mwfire leaving another comment so that the stale bot doesn't come along to close this, still a relevant PR

**Comment by ilijapuaca** [comment]
@mwfire any chance we can get this merged in? It's the only library many of us use that still adds a nasty warning about outdated Swift version.

It's that small of an annoyance that it doesn't justify targeting a custom fork for me :)

**Comment by mwfire** [comment]
Hey everyone! Thx for contributing and apologies for my late reply. I am looking at this currently!

**Pull request merged**
