### PR TITLE
Migrated to Swift 4.2

### PR DESCRIPTION
**Pull request by afnanm1999**
I have successfully migrated the Example app and the PopupDialog Framework to Swift 4.2. This migration was done on Xcode 10 GM Release. Please feel free to reach out to me if you have any concerns. Thanks

### CODE REVIEW

**Review by mwfire — COMMENTED** [review]
Currently, this can not be merged. The changes in the external DynamicBlurView dependency will always be overridden on pod install / pod update and only work locally. Unless DynamicBlurView is Swift 4.2 ready, PopupDialog cannot be fully migrated to Swift 4.2. 

PR for DynamicBlurView can be found here: https://github.com/KyoheiG3/DynamicBlurView/pull/38

**Comment by pushchris** [comment]
@mwfire looks like they merged your Swift 4.2 changes in and updated the Podspec

**Comment by afnanm1999** [comment]
Hey @mwfire 
If you want i can also migrate that framework to Swift 4.2 as well so its full compatible.

**Comment by pushchris** [comment]
@afnanm1999 the author of that framework has already merged Swift 4.2 changes

**Comment by aliondos** [comment]
Hey there... DynamicBlurView Seems to have been updated to Swift 4.2 as of 6 hours ago :)

**Comment by afnanm1999** [comment]
@pushchris @mwfire Okay so sometime tonight i will update the project again. BTW i'm in EST TimeZone. Will keep you guys posted.

**Comment by afnanm1999** [comment]
@mwfire I have applied the changes please double check everything and feel free to contact me if an issue arises. Thanks.

**Comment by pushchris** [comment]
Could we get this merged please?

**Pull request merged**
