### PR TITLE
configuration for carthage

### PR DESCRIPTION
**Pull request by 0x0c**
Hi, I checked `Shared` in `PopupDialog` scheme.
It enables to use PopupDialog with Carthage.

### CODE REVIEW

**Comment by mwfire** [comment]
@0x0c Awesome, thanks! Merged. I have updated the Readme accordingly.

This should work without creating a new version tag, right?

**Comment by 0x0c** [comment]
Thank you for your merge ;)

> This should work without creating a new version tag, right?

No, you have to add a new tag.
I added `0.2.2` tag at my forked repo and it works fine.

**Comment by mwfire** [comment]
@0x0c Just did another test, and it fetched the latest version, which is 0.2.1. That's perfect, so no need to bump version by now. Thanks again!

**Comment by 0x0c** [comment]
OK, thanks :)

**Pull request merged**
