### PR TITLE
Updated to Swift 4.2 Running on Xcode 10 beta 5

### PR DESCRIPTION
**Pull request by afnanm1999**

### CODE REVIEW

**Comment by mwfire** [comment]
Thanks @afnanm1999, I will move the PR to a dedicated Swift 4.2 branch until it is out of beta and eventually merge it. Big up!

**Comment by pushchris** [comment]
@mwfire now that Swift 4.2 is out of beta could this get merged into master? Thanks!

**Comment by afnanm1999** [comment]
Hey @pushchris , 
The latest commit I have on GitHub is actually 5 commits behind this repository. It also hasn't been updated since Xcode 10 Beta 5. I will be pushing a new commit very soon which will be up to date with this repository and as well as the latest Version of Xcode 10.

Thanks,
Afnan

**Comment by pushchris** [comment]
@afnanm1999 that would be great thank you

**Comment by afnanm1999** [comment]
Hey @pushchris ,
I have created a new Pull Request with the most up to date version of this Magnificent framework.
Thanks,
Afnan Mirza

**Pull request closed without merging**
